using System.Security.Cryptography;
using System.Text;

namespace WindowPacTunneling.Services;

public static class PacGenerator
{
    public static (string Content, string Hash) Generate(
        string proxyHost,
        int proxyPort,
        IEnumerable<string> domains,
        IEnumerable<CidrEntry> subnets)
    {
        var domainList = domains
            .Where(x => !string.IsNullOrWhiteSpace(x))
            .Select(x => x.Trim().TrimStart('.'))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(x => x, StringComparer.OrdinalIgnoreCase)
            .ToList();

        var subnetList = subnets
            .Distinct()
            .OrderBy(x => x.Network, StringComparer.Ordinal)
            .ThenBy(x => x.Mask, StringComparer.Ordinal)
            .ToList();

        var proxy = $"PROXY {proxyHost}:{proxyPort}; DIRECT";
        var builder = new StringBuilder();
        builder.AppendLine("// Generated by Window PAC Tunneling");
        builder.AppendLine();
        builder.Append("var PROXY = \"");
        builder.Append(EscapeJs(proxy));
        builder.AppendLine("\";");
        builder.AppendLine();
        AppendStringArray(builder, "HOSTS", domainList);
        builder.AppendLine();
        AppendSubnetArray(builder, "SUBNETS", subnetList);
        builder.AppendLine();
        builder.AppendLine("function FindProxyForURL(url, host) {");
        builder.AppendLine("  var i;");
        builder.AppendLine("  for (i = 0; i < HOSTS.length; i++) {");
        builder.AppendLine("    if (dnsDomainIs(host, HOSTS[i]) || shExpMatch(host, \"*.\" + HOSTS[i])) {");
        builder.AppendLine("      return PROXY;");
        builder.AppendLine("    }");
        builder.AppendLine("  }");
        builder.AppendLine();
        builder.AppendLine("  if (isPlainHostName(host) === false) {");
        builder.AppendLine("    for (i = 0; i < SUBNETS.length; i++) {");
        builder.AppendLine("      if (isInNet(host, SUBNETS[i][0], SUBNETS[i][1])) {");
        builder.AppendLine("        return PROXY;");
        builder.AppendLine("      }");
        builder.AppendLine("    }");
        builder.AppendLine("  }");
        builder.AppendLine();
        builder.AppendLine("  return \"DIRECT\";");
        builder.AppendLine("}");

        var content = builder.ToString();
        var hash = ComputeHash(content);
        return (content, hash);
    }

    private static void AppendStringArray(StringBuilder builder, string name, IReadOnlyList<string> values)
    {
        builder.Append("var ");
        builder.Append(name);
        builder.AppendLine(" = [");

        for (var i = 0; i < values.Count; i++)
        {
            builder.Append("  \"");
            builder.Append(EscapeJs(values[i]));
            builder.Append('"');
            builder.AppendLine(i == values.Count - 1 ? string.Empty : ",");
        }

        builder.AppendLine("];");
    }

    private static void AppendSubnetArray(StringBuilder builder, string name, IReadOnlyList<CidrEntry> values)
    {
        builder.Append("var ");
        builder.Append(name);
        builder.AppendLine(" = [");

        for (var i = 0; i < values.Count; i++)
        {
            var subnet = values[i];
            builder.Append("  [\"");
            builder.Append(EscapeJs(subnet.Network));
            builder.Append("\", \"");
            builder.Append(EscapeJs(subnet.Mask));
            builder.Append('"');
            builder.Append(']');
            builder.AppendLine(i == values.Count - 1 ? string.Empty : ",");
        }

        builder.AppendLine("];");
    }

    private static string EscapeJs(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string ComputeHash(string content)
    {
        var bytes = SHA256.HashData(Encoding.UTF8.GetBytes(content));
        return Convert.ToBase64String(bytes)[..4]
            .Replace('+', 'o')
            .Replace('/', 'A');
    }
}
